# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
codecov: true
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
after_success:
  ## Document given by codecov suggests the following line; however, reports in Travis-CI showed that
  ## "Pkg.dir(...)" is deprecated. So I changed the following line back to the default settings.
  # - julia -e 'using Pkg; cd(Pkg.dir("FiniteDifferenceSchemes")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
